Tdl 19964 add missing tap tester tests
singer-io/tap-typeform pull request #65
Opened 2022-07-27 05:41 UTC by namrata270998

# Description of change
- 

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-07-28 05:26 UTC, savan-chovatiya requested changes

2022-07-29 05:04 UTC, namrata270998 commented on tests/test_typeform_bookmarks.py
> +        simulated_states = {'forms': {'last_updated_at': '2022-07-22T16:00:47Z'}, 'landings': {'mVn2wE55': {'landed_at': '2022-07-21T00:00:00Z'}, 'xJ8emTTy': {'landed_at': '2022-07-24T16:49:54Z'}}, '
Added multiline for better readability

2022-07-29 05:04 UTC, namrata270998 commented on tests/test_typeform_bookmarks.py
> +                                    # replication_key_value = [record.get(replication_key) if record.get('_sdc_form_id') == form_key]
removed commented code

2022-07-29 05:05 UTC, namrata270998 commented on tests/test_typeform_pagination.py
> +#for tap-typeform pagination
removed unwanted comments

2022-07-29 05:05 UTC, namrata270998 commented on tests/test_typeform_start_date.py
> +        • verify all data from later start data has bookmark values >= start_date
Updated to uppercase

2022-07-29 05:05 UTC, namrata270998 commented on tests/test_typeform_bookmarks.py
> +                                        continue
removed the else

2022-07-29 05:05 UTC, namrata270998 commented on tests/test_typeform_bookmarks.py
> +                            if stream != 'answers':
Added comments

2022-07-29 06:37 UTC, savan-chovatiya approved these changes

2022-08-03 05:05 UTC, dbshah1212 approved these changes

2022-08-19 17:20 UTC, kspeer825 approved these changes

2022-08-29 06:59 UTC, merged