TDL-21114 add tags property for submitted_landings stream
singer-io/tap-typeform pull request #75
Opened 2023-05-25 07:51 UTC by kethan1122

# Description of change
Duplicates #68 

# Manual QA steps
 - Created tags for responses available on test account and ran sync to see field being extracted.
 
# Risks
 - Low
 
# Rollback steps
 - revert this branch

2023-05-25 08:13 UTC, RushiT0122 requested changes

2023-05-25 08:13 UTC, RushiT0122 commented on tap_typeform/schemas/submitted_landings.json
> +    },
```suggestion
    "tags": {
      "type": [
        "null",
        "array"
      ],
      "items": {
      "type": [
        "null",
        "string"
      }
    },
```

2023-05-25 08:21 UTC, kethan1122 commented on tap_typeform/schemas/submitted_landings.json
> +    },
Changed

2023-05-25 16:14 UTC, kethan1122 commented on tap_typeform/streams.py
> +                "tags": record["tags"] if "tags" in record else [],
ok.. then is it necessary to have `null` as data type [here](https://github.com/singer-io/tap-typeform/blob/33e560acd9f21c329e620b34c3ba63b9b02c164a/tap_typeform/schemas/submitted_landings.json#L44)

2023-05-26 13:20 UTC, RushiT0122 commented on tap_typeform/schemas/submitted_landings.json
> +    },
I didn't realise it earlier but to keep pattern uniform, can we write schema on the same line?

Otherwise it looks good.

2023-05-26 13:20 UTC, RushiT0122 approved these changes

2023-05-30 17:27 UTC, leslievandemark commented on tap_typeform/streams.py
> +                "tags": record["tags"] if "tags" in record else [],
yes, we should leave the null option in the schema

2023-05-31 14:07 UTC, leslievandemark commented on tap_typeform/schemas/submitted_landings.json
> +        "type": ["string"]
I think you misunderstood my last comment, the `null` should remain in the schema. That will allow null values to persisted if there are any. As it is written here if a null was returned by the API the transformer would throw an error.

2023-05-31 14:15 UTC, leslievandemark approved these changes

2023-05-31 15:20 UTC, merged